// prettier-ignore
export const patternCycles = [7,1,9,4,5,6,14,2,3,4,12,7,1,2,10,5,6,7,8,3,4,5,13,1,2,3,11,6];

export const patterns = [
  {
    pattern_id: 1,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 5,
      endDay: 1,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 2,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 8,
      endDay: 1,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 2,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 21,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 21,
    },
  },
  {
    pattern_id: 2,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 28,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 30,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 5,
      beginningDay: 31,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 31,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 1,
      endMonth: 8,
      endDay: 30,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 8,
      beginningDay: 31,
      endMonth: 9,
      endDay: 30,
      workdays: 21,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 11,
      endDay: 29,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 11,
      beginningDay: 30,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 3,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 28,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 21,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 30,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 5,
      beginningDay: 31,
      endMonth: 6,
      endDay: 30,
      workdays: 21,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 29,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 8,
      beginningDay: 30,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 4,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 28,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 21,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 21,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 5,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 29,
      workdays: 21,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 30,
      endMonth: 2,
      endDay: 28,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 21,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 6,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 21,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 21,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 31,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 1,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 11,
      endDay: 1,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 2,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 7,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 21,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 8,
      endDay: 1,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 2,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 21,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 8,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 2,
      endDay: 29,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 30,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 5,
      beginningDay: 31,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 31,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 1,
      endMonth: 8,
      endDay: 30,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 8,
      beginningDay: 31,
      endMonth: 9,
      endDay: 30,
      workdays: 21,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 11,
      endDay: 29,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 11,
      beginningDay: 30,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 9,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 29,
      workdays: 22,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 21,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 30,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 5,
      beginningDay: 31,
      endMonth: 6,
      endDay: 30,
      workdays: 21,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 29,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 8,
      beginningDay: 30,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 10,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 29,
      workdays: 22,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 21,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 21,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 30,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 10,
      beginningDay: 31,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 11,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 30,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 1,
      beginningDay: 31,
      endMonth: 2,
      endDay: 29,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 1,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 21,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 30,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 7,
      beginningDay: 31,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 12,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 22,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 21,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 22,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 21,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 31,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 1,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 11,
      endDay: 1,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 2,
      endMonth: 12,
      endDay: 1,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 2,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 13,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 21,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 22,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 4,
      endDay: 30,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 1,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 8,
      endDay: 1,
      workdays: 22,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 2,
      endMonth: 8,
      endDay: 31,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 9,
      beginningDay: 1,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 21,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 22,
    },
  },
  {
    pattern_id: 14,
    Jan: {
      beginningMonth: 1,
      beginningDay: 1,
      endMonth: 1,
      endDay: 31,
      workdays: 21,
    },
    Feb: {
      beginningMonth: 2,
      beginningDay: 1,
      endMonth: 3,
      endDay: 1,
      workdays: 22,
    },
    Mar: {
      beginningMonth: 3,
      beginningDay: 2,
      endMonth: 3,
      endDay: 31,
      workdays: 22,
    },
    Apr: {
      beginningMonth: 4,
      beginningDay: 1,
      endMonth: 5,
      endDay: 1,
      workdays: 21,
    },
    May: {
      beginningMonth: 5,
      beginningDay: 2,
      endMonth: 5,
      endDay: 31,
      workdays: 22,
    },
    Jun: {
      beginningMonth: 6,
      beginningDay: 1,
      endMonth: 6,
      endDay: 30,
      workdays: 22,
    },
    Jul: {
      beginningMonth: 7,
      beginningDay: 1,
      endMonth: 7,
      endDay: 31,
      workdays: 21,
    },
    Aug: {
      beginningMonth: 8,
      beginningDay: 1,
      endMonth: 8,
      endDay: 30,
      workdays: 22,
    },
    Sep: {
      beginningMonth: 8,
      beginningDay: 31,
      endMonth: 9,
      endDay: 30,
      workdays: 22,
    },
    Oct: {
      beginningMonth: 10,
      beginningDay: 1,
      endMonth: 10,
      endDay: 31,
      workdays: 22,
    },
    Nov: {
      beginningMonth: 11,
      beginningDay: 1,
      endMonth: 11,
      endDay: 30,
      workdays: 22,
    },
    Dec: {
      beginningMonth: 12,
      beginningDay: 1,
      endMonth: 12,
      endDay: 31,
      workdays: 21,
    },
  },
];
